// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.12.4
// source: proto/bdn9.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetRGBModeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode    uint32 `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Persist bool   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
}

func (x *SetRGBModeRequest) Reset() {
	*x = SetRGBModeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRGBModeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRGBModeRequest) ProtoMessage() {}

func (x *SetRGBModeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRGBModeRequest.ProtoReflect.Descriptor instead.
func (*SetRGBModeRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{0}
}

func (x *SetRGBModeRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *SetRGBModeRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type SetRGBModeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetRGBModeReply) Reset() {
	*x = SetRGBModeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetRGBModeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetRGBModeReply) ProtoMessage() {}

func (x *SetRGBModeReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetRGBModeReply.ProtoReflect.Descriptor instead.
func (*SetRGBModeReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{1}
}

type SetMatrixHSVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H       uint32 `protobuf:"varint,1,opt,name=h,proto3" json:"h,omitempty"`
	S       uint32 `protobuf:"varint,2,opt,name=s,proto3" json:"s,omitempty"`
	V       uint32 `protobuf:"varint,3,opt,name=v,proto3" json:"v,omitempty"`
	Persist bool   `protobuf:"varint,4,opt,name=persist,proto3" json:"persist,omitempty"`
}

func (x *SetMatrixHSVRequest) Reset() {
	*x = SetMatrixHSVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMatrixHSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMatrixHSVRequest) ProtoMessage() {}

func (x *SetMatrixHSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMatrixHSVRequest.ProtoReflect.Descriptor instead.
func (*SetMatrixHSVRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{2}
}

func (x *SetMatrixHSVRequest) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *SetMatrixHSVRequest) GetS() uint32 {
	if x != nil {
		return x.S
	}
	return 0
}

func (x *SetMatrixHSVRequest) GetV() uint32 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *SetMatrixHSVRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type SetMatrixHSVReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetMatrixHSVReply) Reset() {
	*x = SetMatrixHSVReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMatrixHSVReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMatrixHSVReply) ProtoMessage() {}

func (x *SetMatrixHSVReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMatrixHSVReply.ProtoReflect.Descriptor instead.
func (*SetMatrixHSVReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{3}
}

type ToggleMatrixRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persist bool `protobuf:"varint,1,opt,name=persist,proto3" json:"persist,omitempty"`
}

func (x *ToggleMatrixRequest) Reset() {
	*x = ToggleMatrixRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleMatrixRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleMatrixRequest) ProtoMessage() {}

func (x *ToggleMatrixRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleMatrixRequest.ProtoReflect.Descriptor instead.
func (*ToggleMatrixRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{4}
}

func (x *ToggleMatrixRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type ToggleMatrixReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToggleMatrixReply) Reset() {
	*x = ToggleMatrixReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleMatrixReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleMatrixReply) ProtoMessage() {}

func (x *ToggleMatrixReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleMatrixReply.ProtoReflect.Descriptor instead.
func (*ToggleMatrixReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{5}
}

type SetIndicatorHSVRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H       uint32 `protobuf:"varint,1,opt,name=h,proto3" json:"h,omitempty"`
	S       uint32 `protobuf:"varint,2,opt,name=s,proto3" json:"s,omitempty"`
	V       uint32 `protobuf:"varint,3,opt,name=v,proto3" json:"v,omitempty"`
	Key     uint32 `protobuf:"varint,4,opt,name=key,proto3" json:"key,omitempty"`
	Persist bool   `protobuf:"varint,5,opt,name=persist,proto3" json:"persist,omitempty"`
	Layer   uint32 `protobuf:"varint,6,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *SetIndicatorHSVRequest) Reset() {
	*x = SetIndicatorHSVRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIndicatorHSVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIndicatorHSVRequest) ProtoMessage() {}

func (x *SetIndicatorHSVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIndicatorHSVRequest.ProtoReflect.Descriptor instead.
func (*SetIndicatorHSVRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{6}
}

func (x *SetIndicatorHSVRequest) GetH() uint32 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *SetIndicatorHSVRequest) GetS() uint32 {
	if x != nil {
		return x.S
	}
	return 0
}

func (x *SetIndicatorHSVRequest) GetV() uint32 {
	if x != nil {
		return x.V
	}
	return 0
}

func (x *SetIndicatorHSVRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *SetIndicatorHSVRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

func (x *SetIndicatorHSVRequest) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

type SetIndicatorHSVReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetIndicatorHSVReply) Reset() {
	*x = SetIndicatorHSVReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIndicatorHSVReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIndicatorHSVReply) ProtoMessage() {}

func (x *SetIndicatorHSVReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIndicatorHSVReply.ProtoReflect.Descriptor instead.
func (*SetIndicatorHSVReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{7}
}

type ToggleIndicatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Layer uint32 `protobuf:"varint,2,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *ToggleIndicatorRequest) Reset() {
	*x = ToggleIndicatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleIndicatorRequest) ProtoMessage() {}

func (x *ToggleIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleIndicatorRequest.ProtoReflect.Descriptor instead.
func (*ToggleIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{8}
}

func (x *ToggleIndicatorRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ToggleIndicatorRequest) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

type ToggleIndicatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ToggleIndicatorReply) Reset() {
	*x = ToggleIndicatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ToggleIndicatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleIndicatorReply) ProtoMessage() {}

func (x *ToggleIndicatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleIndicatorReply.ProtoReflect.Descriptor instead.
func (*ToggleIndicatorReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{9}
}

type EnableIndicatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Layer uint32 `protobuf:"varint,2,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *EnableIndicatorRequest) Reset() {
	*x = EnableIndicatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIndicatorRequest) ProtoMessage() {}

func (x *EnableIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableIndicatorRequest.ProtoReflect.Descriptor instead.
func (*EnableIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{10}
}

func (x *EnableIndicatorRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *EnableIndicatorRequest) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

type EnableIndicatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EnableIndicatorReply) Reset() {
	*x = EnableIndicatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EnableIndicatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnableIndicatorReply) ProtoMessage() {}

func (x *EnableIndicatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnableIndicatorReply.ProtoReflect.Descriptor instead.
func (*EnableIndicatorReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{11}
}

type DisableIndicatorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   uint32 `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Layer uint32 `protobuf:"varint,2,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *DisableIndicatorRequest) Reset() {
	*x = DisableIndicatorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableIndicatorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIndicatorRequest) ProtoMessage() {}

func (x *DisableIndicatorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableIndicatorRequest.ProtoReflect.Descriptor instead.
func (*DisableIndicatorRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{12}
}

func (x *DisableIndicatorRequest) GetKey() uint32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *DisableIndicatorRequest) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

type DisableIndicatorReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableIndicatorReply) Reset() {
	*x = DisableIndicatorReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableIndicatorReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableIndicatorReply) ProtoMessage() {}

func (x *DisableIndicatorReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableIndicatorReply.ProtoReflect.Descriptor instead.
func (*DisableIndicatorReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{13}
}

type ActivateLayerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer uint32 `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
}

func (x *ActivateLayerRequest) Reset() {
	*x = ActivateLayerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateLayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateLayerRequest) ProtoMessage() {}

func (x *ActivateLayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateLayerRequest.ProtoReflect.Descriptor instead.
func (*ActivateLayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{14}
}

func (x *ActivateLayerRequest) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

type ActivateLayerReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActivateLayerReply) Reset() {
	*x = ActivateLayerReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivateLayerReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateLayerReply) ProtoMessage() {}

func (x *ActivateLayerReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateLayerReply.ProtoReflect.Descriptor instead.
func (*ActivateLayerReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{15}
}

type SetSpeedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Speed   uint32 `protobuf:"varint,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Persist bool   `protobuf:"varint,2,opt,name=persist,proto3" json:"persist,omitempty"`
}

func (x *SetSpeedRequest) Reset() {
	*x = SetSpeedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpeedRequest) ProtoMessage() {}

func (x *SetSpeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpeedRequest.ProtoReflect.Descriptor instead.
func (*SetSpeedRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{16}
}

func (x *SetSpeedRequest) GetSpeed() uint32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *SetSpeedRequest) GetPersist() bool {
	if x != nil {
		return x.Persist
	}
	return false
}

type SetSpeedReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetSpeedReply) Reset() {
	*x = SetSpeedReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetSpeedReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetSpeedReply) ProtoMessage() {}

func (x *SetSpeedReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetSpeedReply.ProtoReflect.Descriptor instead.
func (*SetSpeedReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{17}
}

type SetMuteStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Muted bool `protobuf:"varint,1,opt,name=muted,proto3" json:"muted,omitempty"`
}

func (x *SetMuteStatusRequest) Reset() {
	*x = SetMuteStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMuteStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMuteStatusRequest) ProtoMessage() {}

func (x *SetMuteStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMuteStatusRequest.ProtoReflect.Descriptor instead.
func (*SetMuteStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{18}
}

func (x *SetMuteStatusRequest) GetMuted() bool {
	if x != nil {
		return x.Muted
	}
	return false
}

type SetMuteStatusReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetMuteStatusReply) Reset() {
	*x = SetMuteStatusReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetMuteStatusReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMuteStatusReply) ProtoMessage() {}

func (x *SetMuteStatusReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMuteStatusReply.ProtoReflect.Descriptor instead.
func (*SetMuteStatusReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{19}
}

type EndCallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndCallRequest) Reset() {
	*x = EndCallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndCallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallRequest) ProtoMessage() {}

func (x *EndCallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallRequest.ProtoReflect.Descriptor instead.
func (*EndCallRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{20}
}

type EndCallReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EndCallReply) Reset() {
	*x = EndCallReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EndCallReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndCallReply) ProtoMessage() {}

func (x *EndCallReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndCallReply.ProtoReflect.Descriptor instead.
func (*EndCallReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{21}
}

type ResetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetRequest) Reset() {
	*x = ResetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetRequest) ProtoMessage() {}

func (x *ResetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetRequest.ProtoReflect.Descriptor instead.
func (*ResetRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{22}
}

type ResetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ResetReply) Reset() {
	*x = ResetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetReply) ProtoMessage() {}

func (x *ResetReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetReply.ProtoReflect.Descriptor instead.
func (*ResetReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{23}
}

type EchoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{24}
}

type EchoReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EchoReply) Reset() {
	*x = EchoReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_bdn9_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoReply) ProtoMessage() {}

func (x *EchoReply) ProtoReflect() protoreflect.Message {
	mi := &file_proto_bdn9_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoReply.ProtoReflect.Descriptor instead.
func (*EchoReply) Descriptor() ([]byte, []int) {
	return file_proto_bdn9_proto_rawDescGZIP(), []int{25}
}

var File_proto_bdn9_proto protoreflect.FileDescriptor

var file_proto_bdn9_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x64, 0x6e, 0x39, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x41, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x52, 0x47, 0x42, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70,
	0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x52, 0x47, 0x42, 0x4d,
	0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x59, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x4d,
	0x61, 0x74, 0x72, 0x69, 0x78, 0x48, 0x53, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x0c, 0x0a, 0x01, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x68, 0x12, 0x0c, 0x0a,
	0x01, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x76,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x76, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72,
	0x73, 0x69, 0x73, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73,
	0x69, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78,
	0x48, 0x53, 0x56, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2f, 0x0a, 0x13, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x54, 0x6f, 0x67,
	0x67, 0x6c, 0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x84,
	0x01, 0x0a, 0x16, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x48,
	0x53, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x68, 0x12, 0x0c, 0x0a, 0x01, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x01, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x01, 0x76, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x48, 0x53, 0x56, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x40, 0x0a,
	0x16, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22,
	0x16, 0x0a, 0x14, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x40, 0x0a, 0x16, 0x45, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x16, 0x0a, 0x14, 0x45, 0x6e, 0x61,
	0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x41, 0x0a, 0x17, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x17, 0x0a, 0x15, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x49,
	0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x0a,
	0x14, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x22, 0x14, 0x0a, 0x12, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x41, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x53, 0x70, 0x65, 0x65, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x05, 0x73, 0x70, 0x65, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x65,
	0x72, 0x73, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x65, 0x72,
	0x73, 0x69, 0x73, 0x74, 0x22, 0x0f, 0x0a, 0x0d, 0x53, 0x65, 0x74, 0x53, 0x70, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2c, 0x0a, 0x14, 0x53, 0x65, 0x74, 0x4d, 0x75, 0x74, 0x65,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x6d, 0x75, 0x74, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6d, 0x75,
	0x74, 0x65, 0x64, 0x22, 0x14, 0x0a, 0x12, 0x53, 0x65, 0x74, 0x4d, 0x75, 0x74, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x0a, 0x0e, 0x45, 0x6e, 0x64,
	0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0e, 0x0a, 0x0c, 0x45,
	0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0e, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0c, 0x0a, 0x0a, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x0d, 0x0a, 0x0b, 0x45, 0x63, 0x68,
	0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x0b, 0x0a, 0x09, 0x45, 0x63, 0x68, 0x6f,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xf8, 0x05, 0x0a, 0x0b, 0x42, 0x44, 0x4e, 0x39, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a, 0x0a, 0x53, 0x65, 0x74, 0x52, 0x47, 0x42, 0x4d,
	0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x47, 0x42, 0x4d, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x10, 0x2e, 0x53, 0x65, 0x74, 0x52, 0x47, 0x42,
	0x4d, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0c, 0x53,
	0x65, 0x74, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x48, 0x53, 0x56, 0x12, 0x14, 0x2e, 0x53, 0x65,
	0x74, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x48, 0x53, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x12, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x48, 0x53, 0x56,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0c, 0x54, 0x6f, 0x67, 0x67, 0x6c,
	0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x12, 0x14, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65,
	0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e,
	0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x4d, 0x61, 0x74, 0x72, 0x69, 0x78, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0f, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x48, 0x53, 0x56, 0x12, 0x17, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69,
	0x63, 0x61, 0x74, 0x6f, 0x72, 0x48, 0x53, 0x56, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x15, 0x2e, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x48, 0x53,
	0x56, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a, 0x0f, 0x54, 0x6f, 0x67, 0x67,
	0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x17, 0x2e, 0x54, 0x6f,
	0x67, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x54, 0x6f, 0x67, 0x67, 0x6c, 0x65, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x43, 0x0a,
	0x0f, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x17, 0x2e, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74,
	0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x45, 0x6e, 0x61, 0x62,
	0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x46, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64,
	0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x12, 0x18, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x49, 0x6e, 0x64, 0x69, 0x63, 0x61, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x6e, 0x64, 0x69, 0x63, 0x61,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x12, 0x15, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x13, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x4c, 0x61, 0x79,
	0x65, 0x72, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2e, 0x0a, 0x08, 0x53, 0x65, 0x74,
	0x53, 0x70, 0x65, 0x65, 0x64, 0x12, 0x10, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x65, 0x65, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0e, 0x2e, 0x53, 0x65, 0x74, 0x53, 0x70, 0x65,
	0x65, 0x64, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0d, 0x53, 0x65, 0x74,
	0x4d, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x15, 0x2e, 0x53, 0x65, 0x74,
	0x4d, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x13, 0x2e, 0x53, 0x65, 0x74, 0x4d, 0x75, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2b, 0x0a, 0x07, 0x45, 0x6e, 0x64, 0x43,
	0x61, 0x6c, 0x6c, 0x12, 0x0f, 0x2e, 0x45, 0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x0d, 0x2e, 0x45, 0x6e, 0x64, 0x43, 0x61, 0x6c, 0x6c, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x25, 0x0a, 0x05, 0x52, 0x65, 0x73, 0x65, 0x74, 0x12, 0x0d,
	0x2e, 0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0b, 0x2e,
	0x52, 0x65, 0x73, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x22, 0x0a, 0x04,
	0x45, 0x63, 0x68, 0x6f, 0x12, 0x0c, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x0a, 0x2e, 0x45, 0x63, 0x68, 0x6f, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6e, 0x64, 0x79, 0x74, 0x68, 0x69, 0x67, 0x70, 0x65, 0x6e, 0x2f, 0x62, 0x64, 0x6e, 0x39, 0x5f,
	0x63, 0x6f, 0x6d, 0x70, 0x2f, 0x76, 0x32, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_bdn9_proto_rawDescOnce sync.Once
	file_proto_bdn9_proto_rawDescData = file_proto_bdn9_proto_rawDesc
)

func file_proto_bdn9_proto_rawDescGZIP() []byte {
	file_proto_bdn9_proto_rawDescOnce.Do(func() {
		file_proto_bdn9_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_bdn9_proto_rawDescData)
	})
	return file_proto_bdn9_proto_rawDescData
}

var file_proto_bdn9_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_bdn9_proto_goTypes = []interface{}{
	(*SetRGBModeRequest)(nil),       // 0: SetRGBModeRequest
	(*SetRGBModeReply)(nil),         // 1: SetRGBModeReply
	(*SetMatrixHSVRequest)(nil),     // 2: SetMatrixHSVRequest
	(*SetMatrixHSVReply)(nil),       // 3: SetMatrixHSVReply
	(*ToggleMatrixRequest)(nil),     // 4: ToggleMatrixRequest
	(*ToggleMatrixReply)(nil),       // 5: ToggleMatrixReply
	(*SetIndicatorHSVRequest)(nil),  // 6: SetIndicatorHSVRequest
	(*SetIndicatorHSVReply)(nil),    // 7: SetIndicatorHSVReply
	(*ToggleIndicatorRequest)(nil),  // 8: ToggleIndicatorRequest
	(*ToggleIndicatorReply)(nil),    // 9: ToggleIndicatorReply
	(*EnableIndicatorRequest)(nil),  // 10: EnableIndicatorRequest
	(*EnableIndicatorReply)(nil),    // 11: EnableIndicatorReply
	(*DisableIndicatorRequest)(nil), // 12: DisableIndicatorRequest
	(*DisableIndicatorReply)(nil),   // 13: DisableIndicatorReply
	(*ActivateLayerRequest)(nil),    // 14: ActivateLayerRequest
	(*ActivateLayerReply)(nil),      // 15: ActivateLayerReply
	(*SetSpeedRequest)(nil),         // 16: SetSpeedRequest
	(*SetSpeedReply)(nil),           // 17: SetSpeedReply
	(*SetMuteStatusRequest)(nil),    // 18: SetMuteStatusRequest
	(*SetMuteStatusReply)(nil),      // 19: SetMuteStatusReply
	(*EndCallRequest)(nil),          // 20: EndCallRequest
	(*EndCallReply)(nil),            // 21: EndCallReply
	(*ResetRequest)(nil),            // 22: ResetRequest
	(*ResetReply)(nil),              // 23: ResetReply
	(*EchoRequest)(nil),             // 24: EchoRequest
	(*EchoReply)(nil),               // 25: EchoReply
}
var file_proto_bdn9_proto_depIdxs = []int32{
	0,  // 0: BDN9Service.SetRGBMode:input_type -> SetRGBModeRequest
	2,  // 1: BDN9Service.SetMatrixHSV:input_type -> SetMatrixHSVRequest
	4,  // 2: BDN9Service.ToggleMatrix:input_type -> ToggleMatrixRequest
	6,  // 3: BDN9Service.SetIndicatorHSV:input_type -> SetIndicatorHSVRequest
	8,  // 4: BDN9Service.ToggleIndicator:input_type -> ToggleIndicatorRequest
	10, // 5: BDN9Service.EnableIndicator:input_type -> EnableIndicatorRequest
	12, // 6: BDN9Service.DisableIndicator:input_type -> DisableIndicatorRequest
	14, // 7: BDN9Service.ActivateLayer:input_type -> ActivateLayerRequest
	16, // 8: BDN9Service.SetSpeed:input_type -> SetSpeedRequest
	18, // 9: BDN9Service.SetMuteStatus:input_type -> SetMuteStatusRequest
	20, // 10: BDN9Service.EndCall:input_type -> EndCallRequest
	22, // 11: BDN9Service.Reset:input_type -> ResetRequest
	24, // 12: BDN9Service.Echo:input_type -> EchoRequest
	1,  // 13: BDN9Service.SetRGBMode:output_type -> SetRGBModeReply
	3,  // 14: BDN9Service.SetMatrixHSV:output_type -> SetMatrixHSVReply
	5,  // 15: BDN9Service.ToggleMatrix:output_type -> ToggleMatrixReply
	7,  // 16: BDN9Service.SetIndicatorHSV:output_type -> SetIndicatorHSVReply
	9,  // 17: BDN9Service.ToggleIndicator:output_type -> ToggleIndicatorReply
	11, // 18: BDN9Service.EnableIndicator:output_type -> EnableIndicatorReply
	13, // 19: BDN9Service.DisableIndicator:output_type -> DisableIndicatorReply
	15, // 20: BDN9Service.ActivateLayer:output_type -> ActivateLayerReply
	17, // 21: BDN9Service.SetSpeed:output_type -> SetSpeedReply
	19, // 22: BDN9Service.SetMuteStatus:output_type -> SetMuteStatusReply
	21, // 23: BDN9Service.EndCall:output_type -> EndCallReply
	23, // 24: BDN9Service.Reset:output_type -> ResetReply
	25, // 25: BDN9Service.Echo:output_type -> EchoReply
	13, // [13:26] is the sub-list for method output_type
	0,  // [0:13] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_bdn9_proto_init() }
func file_proto_bdn9_proto_init() {
	if File_proto_bdn9_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_bdn9_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRGBModeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetRGBModeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMatrixHSVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMatrixHSVReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleMatrixRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleMatrixReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIndicatorHSVRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIndicatorHSVReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleIndicatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ToggleIndicatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableIndicatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EnableIndicatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableIndicatorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableIndicatorReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateLayerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivateLayerReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpeedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetSpeedReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMuteStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetMuteStatusReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndCallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EndCallReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_bdn9_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_bdn9_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_bdn9_proto_goTypes,
		DependencyIndexes: file_proto_bdn9_proto_depIdxs,
		MessageInfos:      file_proto_bdn9_proto_msgTypes,
	}.Build()
	File_proto_bdn9_proto = out.File
	file_proto_bdn9_proto_rawDesc = nil
	file_proto_bdn9_proto_goTypes = nil
	file_proto_bdn9_proto_depIdxs = nil
}
